### ISSUE TITLE
While doing npm i i am getting error (npm ERR! premature close)

### ISSUE THREAD

**Issue by prk2331** [canbax/davraz#3] opened 2021-12-03 11:48 UTC
I am using node version ->v14.17.5
                  npm version -> 6.14.14
 
Error :
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! premature close

Please help me out!

and I am unable to find out: proxy_server.js file

**Comment by canbax** [comment] 2021-12-03 19:16
where do you get the error? Is it during ˋnpm installˋ? 

I moved proxy server to a separate project. Soryy I will change readme.

https://github.com/canbax/tiger-api

**Comment by prk2331** [comment] 2021-12-04 04:08
yes I am facing while doing npm install 
here below are the version which I am using

I am using node version ->v14.17.5
npm version -> 6.14.14

**Detail error** :
**npm install**
npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142     
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! premature close

**Comment by canbax** [comment] 2021-12-04 08:27
@prk2331  I just solved this! Please close if it is fixed now. 

The issue is some dependency has a corrupted package.json file. I fixed that dependency with commit https://github.com/iVis-at-Bilkent/cytoscape.js-chola/commit/95e010ecd1a86af0ab0caf5087893e6f6fc5c9aa Also since I don't use those dependencies I also removed them. 

Check now. I checked with "npm 6.14.14" and "node v16.13.1". `npm i` and then `npm run start` works fine. Thank you.

**Comment by prk2331** [comment] 2021-12-04 17:44
@canbax 
Thanks for your response Really appreciated!
Yaa I checked its working now with node JS Backend,
Can you please provide me quick guidance,  
I connect it with tigerGraph, But I am unable to get the SVG icons on the nodes,
which is in my graph schema, can you please provide some guidance on this ?

**Comment by canbax** [comment] 2021-12-04 19:06
Styles and icons in the tiger graph are totally unrelated. Here we make visualization with [cytoscape.js](https://js.cytoscape.org/) So you should give [cytoscape.js styles](https://js.cytoscape.org/#style) 

For a sample, you can load https://github.com/canbax/davraz/blob/master/src/assets/cytoscape.js-style/covid19.json with "File>Load Graph Style" and then you can load a graph compatible with this style.  You can load a graph such as https://github.com/canbax/davraz/blob/master/src/assets/sample_data/covid-19-sample-data.json with "File>Load"

**Comment by prk2331** [comment] 2021-12-05 18:42
@canbax yes I checked the visualization by (Loading Covid 19 data and Covid 19 syling) this is working perfect 
I also check the table format , and Layout algorithms (circle , Grid, fcose, euler, grid etc).
I checked with TigerGraph connection as well  
when I click on the RUN Installed Queries and pass params accordingly which are required, then the  nodes are also coming well in Grey color I explore their neighbor's (Neighbors are also coming in grey color) , But here I am trying to implement (that there is any way to give the different colors to the nodes like for example **All profiles nodes are of red  color** :-(liked Products)- **All Products are in Pink** and so on..  in that way) just for differentiate the (vertices/nodes) in the large Schema
Can you please guide me for that, this will be really helpful.

**Comment by canbax** [comment] 2021-12-05 18:49
You should write your own styles. You can inspect the covid 19 style file and read the docs about cytoscape.js styles

**Comment by prk2331** [comment] 2021-12-07 08:40
@canbax thanks 
I understood the whole concept we will be able to give the Style in Json file according to the rendered Nodes and load the Json file via  **Load Graph style** tab  
But here I am facing an issue that when we load the data from Sample data like COVID data which is given in the sample folder 
then clear the rendered graph, after that when we run our Installed GSQL queries nodes are not coming 
**so this happens only when we load Sample data and then we clear and run our installed query** 
can you please provide some help!

**Comment by canbax** [comment] 2021-12-07 18:27
You should also clear the styles. The data and styles are 2 different things. The data and styles should also be compatible. If you load a data, you should use compatible styles.

**Comment by prk2331** [comment] 2021-12-08 16:24
@canbax Thank you so much,  I got it

**Closed as completed** 2021-12-08 16:58 UTC
